//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Sharpex.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MARPAC_CorporativaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MARPAC_CorporativaEntities object using the connection string found in the 'MARPAC_CorporativaEntities' section of the application configuration file.
        /// </summary>
        public MARPAC_CorporativaEntities() : base("name=MARPAC_CorporativaEntities", "MARPAC_CorporativaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MARPAC_CorporativaEntities object.
        /// </summary>
        public MARPAC_CorporativaEntities(string connectionString) : base(connectionString, "MARPAC_CorporativaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MARPAC_CorporativaEntities object.
        /// </summary>
        public MARPAC_CorporativaEntities(EntityConnection connection) : base(connection, "MARPAC_CorporativaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RegimenesFiscale> RegimenesFiscales
        {
            get
            {
                if ((_RegimenesFiscales == null))
                {
                    _RegimenesFiscales = base.CreateObjectSet<RegimenesFiscale>("RegimenesFiscales");
                }
                return _RegimenesFiscales;
            }
        }
        private ObjectSet<RegimenesFiscale> _RegimenesFiscales;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RegimenesFiscales EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRegimenesFiscales(RegimenesFiscale regimenesFiscale)
        {
            base.AddObject("RegimenesFiscales", regimenesFiscale);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MARPAC_CorporativaModel", Name="RegimenesFiscale")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RegimenesFiscale : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RegimenesFiscale object.
        /// </summary>
        /// <param name="codigoRegimen">Initial value of the CodigoRegimen property.</param>
        /// <param name="nombreRegimen">Initial value of the NombreRegimen property.</param>
        /// <param name="pideCURP">Initial value of the PideCURP property.</param>
        /// <param name="activo">Initial value of the Activo property.</param>
        public static RegimenesFiscale CreateRegimenesFiscale(global::System.Int32 codigoRegimen, global::System.String nombreRegimen, global::System.String pideCURP, global::System.String activo)
        {
            RegimenesFiscale regimenesFiscale = new RegimenesFiscale();
            regimenesFiscale.CodigoRegimen = codigoRegimen;
            regimenesFiscale.NombreRegimen = nombreRegimen;
            regimenesFiscale.PideCURP = pideCURP;
            regimenesFiscale.Activo = activo;
            return regimenesFiscale;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CodigoRegimen
        {
            get
            {
                return _CodigoRegimen;
            }
            set
            {
                if (_CodigoRegimen != value)
                {
                    OnCodigoRegimenChanging(value);
                    ReportPropertyChanging("CodigoRegimen");
                    _CodigoRegimen = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CodigoRegimen");
                    OnCodigoRegimenChanged();
                }
            }
        }
        private global::System.Int32 _CodigoRegimen;
        partial void OnCodigoRegimenChanging(global::System.Int32 value);
        partial void OnCodigoRegimenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreRegimen
        {
            get
            {
                return _NombreRegimen;
            }
            set
            {
                OnNombreRegimenChanging(value);
                ReportPropertyChanging("NombreRegimen");
                _NombreRegimen = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreRegimen");
                OnNombreRegimenChanged();
            }
        }
        private global::System.String _NombreRegimen;
        partial void OnNombreRegimenChanging(global::System.String value);
        partial void OnNombreRegimenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PideCURP
        {
            get
            {
                return _PideCURP;
            }
            set
            {
                OnPideCURPChanging(value);
                ReportPropertyChanging("PideCURP");
                _PideCURP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PideCURP");
                OnPideCURPChanged();
            }
        }
        private global::System.String _PideCURP;
        partial void OnPideCURPChanging(global::System.String value);
        partial void OnPideCURPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Activo
        {
            get
            {
                return _Activo;
            }
            set
            {
                OnActivoChanging(value);
                ReportPropertyChanging("Activo");
                _Activo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Activo");
                OnActivoChanged();
            }
        }
        private global::System.String _Activo;
        partial void OnActivoChanging(global::System.String value);
        partial void OnActivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_UsuarioAlta
        {
            get
            {
                return _ID_UsuarioAlta;
            }
            set
            {
                OnID_UsuarioAltaChanging(value);
                ReportPropertyChanging("ID_UsuarioAlta");
                _ID_UsuarioAlta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_UsuarioAlta");
                OnID_UsuarioAltaChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_UsuarioAlta;
        partial void OnID_UsuarioAltaChanging(Nullable<global::System.Int32> value);
        partial void OnID_UsuarioAltaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RegistroAlta
        {
            get
            {
                return _RegistroAlta;
            }
            set
            {
                OnRegistroAltaChanging(value);
                ReportPropertyChanging("RegistroAlta");
                _RegistroAlta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegistroAlta");
                OnRegistroAltaChanged();
            }
        }
        private Nullable<global::System.DateTime> _RegistroAlta;
        partial void OnRegistroAltaChanging(Nullable<global::System.DateTime> value);
        partial void OnRegistroAltaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID_UsuarioCambio
        {
            get
            {
                return _ID_UsuarioCambio;
            }
            set
            {
                OnID_UsuarioCambioChanging(value);
                ReportPropertyChanging("ID_UsuarioCambio");
                _ID_UsuarioCambio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_UsuarioCambio");
                OnID_UsuarioCambioChanged();
            }
        }
        private Nullable<global::System.Int32> _ID_UsuarioCambio;
        partial void OnID_UsuarioCambioChanging(Nullable<global::System.Int32> value);
        partial void OnID_UsuarioCambioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RegistroCambio
        {
            get
            {
                return _RegistroCambio;
            }
            set
            {
                OnRegistroCambioChanging(value);
                ReportPropertyChanging("RegistroCambio");
                _RegistroCambio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegistroCambio");
                OnRegistroCambioChanged();
            }
        }
        private Nullable<global::System.DateTime> _RegistroCambio;
        partial void OnRegistroCambioChanging(Nullable<global::System.DateTime> value);
        partial void OnRegistroCambioChanged();

        #endregion
    
    }

    #endregion
    
}
