/*
 * File: tabPanel.ui.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

tabPanelUi = Ext.extend(Ext.TabPanel, {
    title: 'My Panel',
    width: 400,
    height: 400,
    activeTab: 0,
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                title: 'Dashboard'
            }
        ];
        tabPanelUi.superclass.initComponent.call(this);
    }
});
